services:
  schemas-test-db:
    image: postgres:17
    container_name: schemas
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5492:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
