version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "dhth"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "dhth"
